AWSTemplateFormatVersion: 2010-09-09
Description: projet1 instance ADM
Parameters:
  KeyName:
    Default: tp1GB
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: t2.micro
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC ID'
#    Default: vpc-033c4fd4afa6a3b73
  SubnetIdPub:
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID public'
#  SubnetIdPriv:
#    Type: AWS::EC2::Subnet::Id
#    Description: 'The Subnet ID private'
  TypeName:
    Type: String
    Description: 'Type de serveur'
    AllowedValues:
      - jenkins
      - nexus
  IngressPort:
    Type: String
    Description: 'Port administration jenkins (8080) ou nexus(8081)'
    AllowedValues:
      - '8080'
      - '8081'
  Urlscript:
    Type: String
    Description: 'command du script'
    AllowedValues:
      - 'sudo wget -O /tmp/install_jenkins.sh https://raw.githubusercontent.com/KevinGit31/depot_projet_1_file_rouge/dev/infra/install_jenkins.sh && chmod +x /tmp/install_jenkins.sh && sudo /bin/bash /tmp/install_jenkins.sh'
      - 'sudo wget -O /tmp/install_nexus.sh https://raw.githubusercontent.com/KevinGit31/depot_projet_1_file_rouge/dev/infra/install_nexus.sh && chmod +x /tmp/install_nexus.sh && sudo /bin/bash /tmp/install_nexus.sh'

  SecurityGroupId:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Description: 'The Security Group ID'

Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t2.micro:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    eu-west-2:
      HVM64: ami-0194c3e07668a7e36
#      HVM64: ami-033af134328c47f48
      HVMG2: NOT_SUPPORTED

Resources:
  Grp3SecurityGroupingress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref SecurityGroupId
      IpProtocol: tcp
      FromPort: !Ref IngressPort
      ToPort: !Ref IngressPort
      CidrIp: 0.0.0.0/0
#Mise en place du groupe de seucrité


#  JenkinsInstance:
#    Type: 'AWS::EC2::Instance'
#    Metadata:
#      'AWS::CloudFormation::Init':
#        configSets:
#          InstallAndRun:
#            - Install
#        Install:
#          packages:
#            apt:
#              git: []
#      'AWS::CloudFormation::Designer':
#        id: ae2c342c-13ef-475f-9510-537822d10859
#    Properties:
#      ImageId: !FindInMap
#        - AWSRegionArch2AMI
#        - !Ref 'AWS::Region'
#        - !FindInMap
#          - AWSInstanceType2Arch
#          - !Ref InstanceType
#          - Arch
#      InstanceType: !Ref InstanceType
#      SecurityGroups:
#        - !Ref Grp3SecurityGroup
#      KeyName: !Ref KeyName
#      UserData: !Base64
#        'Fn::Join':
#          - ''
#          - - |
#              #!/bin/bash -xe
#            - |
#              wget -O install_jenkins.sh https://github.com/KevinGit31/depot_projet_1_file_rouge/infra/aws_cloudformation/raw/dev/install_jenkins.sh | /bin/bash
#              sleep 30s
#              cat /var/lib/jenkins/secrets/initialAdminPassword | xargs echo
#    CreationPolicy:
#      ResourceSignal:
#        Timeout: PT5M

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetIdPub
      SecurityGroupIds:
        - !Ref SecurityGroupId
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - !Ref Urlscript
      Tags:
       - Key: Name
         Value: !Ref TypeName




Outputs:
  WebsiteURL:
    Description: URL for newly created LAMP stack
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - EC2Instance
          - PublicDnsName


Metadata:
  'AWS::CloudFormation::Designer':
    bfea2c56-be77-47d7-9ddb-bb401fea53b8:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    ae2c342c-13ef-475f-9510-537822d10859:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - bfea2c56-be77-47d7-9ddb-bb401fea53b8