AWSTemplateFormatVersion: 2010-09-09
Description: projet1
Parameters:
  KeyName:
    Default: projet1grp3_key
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

Resources:
#Creation d'un vpc
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.80.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
#      InstanceTenancy: default
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC-GRP3" ]]
#Creation d'une passerelle internet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
#Rattachement de la passerelle internet au VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
#Creation d'un sous-reseau public
  PublicSubnetADM:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.40.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-ADM
  PublicSubnetDEV:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.10.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-DEV
  PublicSubnetQUA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.20.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-QUA
  PublicSubnetPROD:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.30.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-PROD

#Creation d'un sous-reseau private
  PrivateSubnetADM:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.140.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-ADM
  PrivateSubnetADM2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.141.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-ADM2
  PrivateSubnetDEV:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.110.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-DEV
  PrivateSubnetQUA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.120.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-QUA
  PrivateSubnetPROD:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.80.130.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-PROD

#########
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
#      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnetADM
      Tags:
      - Key: Name
        Value: !Sub NATPUBGW1-${AWS::StackName}

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
#      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnetDEV
      Tags:
      - Key: Name
        Value: !Sub NATPUBGW2-${AWS::StackName}

  NatGateway3:
    Type: AWS::EC2::NatGateway
    Properties:
#      AllocationId: !GetAtt NatGateway3EIP.AllocationId
      SubnetId: !Ref PublicSubnetQUA
      Tags:
      - Key: Name
        Value: !Sub NATPUBGW3-${AWS::StackName}

  NatGateway4:
    Type: AWS::EC2::NatGateway
    Properties:
#      AllocationId: !GetAtt NatGateway4EIP.AllocationId
      SubnetId: !Ref PublicSubnetPROD
      Tags:
      - Key: Name
        Value: !Sub NATPUBGW4-${AWS::StackName}


###########

#Creation d'une table de route
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: PublicRoute-GRP3
#Creation d'une route vers la passerelle internet
  PublicRoute1:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
#      GatewayId: !Ref InternetGateway
      NatGatewayId: !Ref NATGateway1

#Creation d'une table de route private
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: PrivateRoute-GRP3
#Creation d'une route vers la passerelle internet
#  PublicRoute1:
#    Type: AWS::EC2::Route
#    Properties:
#      RouteTableId: !Ref PrivateRouteTable
#      DestinationCidrBlock: 0.0.0.0/0
#      NatGatewayId: ???

#Association du sous-reseau public à la table de route
  PublicSubnetADMRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetADM
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetDEVRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetDEV
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetQUARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetQUA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetPRODRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetPROD
      RouteTableId: !Ref PublicRouteTable

#Association du sous-reseau private à la table de route
  PrivateSubnetADMRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetADM
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetADM2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetADM2
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetDEVRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetDEV
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetQUARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetQUA
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetPRODRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetPROD
      RouteTableId: !Ref PrivateRouteTable


Outputs:
  VpcId:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref PublicSubnetADM ]]

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnetDEV

  PublicSubnet2:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnetQUA

  PublicSubnet3:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnetPROD

  PrivateSubnetsADM:
    Description: A list of the Private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnetADM ]]

  PrivateSubnetsADM2:
    Description: A list of the Private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnetADM2 ]]

  PrivateSubnet1:
    Description: A reference to the Private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnetDEV

  PrivateSubnet2:
    Description: A reference to the Private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnetQUA

  PrivateSubnet3:
    Description: A reference to the Private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnetPROD


