- name: Add a new user named devops
  user:
    name: devops
    shell: /bin/bash
    password: "{{ secret_devops }}"
- name: Add devops user to the sudoers
  copy:
    dest: "/etc/sudoers.d/devops"
    content: "devops  ALL=(ALL)  NOPASSWD: ALL"
- name: Deploy SSH Key
  authorized_key:
    user: devops
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    state: present
- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regex: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh

handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
