---
- name: create a cloudformation stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: try to get facts about a stack but fail if it doesn't exist
    cloudformation_info:
      stack_name: "{{ TypeName }}"
      all_facts: yes
    failed_when: cloudformation['TypeName'] is undefined
    ignore_errors: true
    register: stackstate
  - name: delete a stack
    cloudformation:
      stack_name: "{{ TypeName }}"
      region: "{{ REGION }}"
      state: "absent"
    when: stackstate.failed_when_result == true