---
- name: create a cloudformation stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: create a cloudformation stack task
    cloudformation:
      stack_name: "{{ TypeName }}"
      state: "present"
      region: "{{ REGION }}"
      disable_rollback: true
      template: "instancegrp3.yaml"
      template_parameters:
        KeyName: "{{ KEYNAME }}"
        Environnement: "{{ ansible_environnement }}"
        RootKey: "{{ RootKey }}"
        JenkinsKey: "{{ JenkinsKey }}"
        DevOpsKey: "{{ secret_devops }}"
        AnsibleKey: "{{ AnsibleKey }}"
        SubnetIdPubADM: "{{ SubnetIdPubADM }}"
        SubnetIdPrivADM: "{{ SubnetIdPrivADM }}"
        SubnetIdPubDEV: "{{ SubnetIdPubDEV }}"
        SubnetIdPrivDEV: "{{ SubnetIdPrivDEV }}"
        SubnetIdPubQUA: "{{ SubnetIdPubQUA }}"
        SubnetIdPrivQUA: "{{ SubnetIdPrivQUA }}"
        SubnetIdPubPROD: "{{ SubnetIdPubPROD }}"
        SubnetIdPrivPROD: "{{ SubnetIdPrivPROD }}"
        VpcId: "{{ VpcId }}"
        PrivateIP: "{{ PrivateIP }}"
        TypeName: "{{ TypeName }}"
        IngressPort: "{{ IngressPort }}"
        SecurityGroupNameList: "{{ SecurityGroupNameList }}"
        Urlscript: "{{ Urlscript }}"
        SecurityGroupId: "{{ SecurityGroupId }}"
        InstanceType: "{{ InstanceType }}"
        AWSAccessKeyId: "{{ AWSAccessKeyId }}"
        AWSSecretAccessKeyId: "{{ AWSSecretAccessKeyId }}"
#      tags:
#        - cloudcreate: "ansible-cloudformation-create"
    register: stack
  - name: stack outputs
    debug: msg="Stack outputs are {{stack.stack_outputs}}"