---
- name: create a cloudformation stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: delete a stack
    cloudformation:
      # aws_access_key: "{{ AWSAccessKeyId }}"
      # aws_secret_key: "{{ AWSSecretAccessKeyId }}"
      stack_name: "{{ TypeName }}"
      region: "{{ REGION }}"
      state: "absent"
    backoff_max_delay: 40
    # tags:
    #   - clouddelete: "ansible-cloudformation-delete"
    # when: GOTODEL == "yes"