---
- name: create a cloudformation stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: try to get facts about a stack but fail if it doesn't exist
    amazon.aws.cloudformation_info:
      stack_name: "{{ TypeName }}"
      all_facts: yes
    failed_when: cloudformation['TypeName'] is undefined
    register: stackstate
  - debug: "{{ stackstate }}"
    when: stackstate.failed_when_result == false
  - name: delete a stack
    amazon.aws.cloudformation:
      # aws_access_key: "{{ AWSAccessKeyId }}"
      # aws_secret_key: "{{ AWSSecretAccessKeyId }}"
      stack_name: "{{ TypeName }}"
      region: "{{ REGION }}"
      state: "absent"
    when: stackstate.failed_when_result == false