- name: Install python3.x86_64
  yum:
    name: python3.x86_64
    state: present
    update_cache: true
- name: Install python3-pip.noarch
  yum:
    name: python3-pip.noarch
    state: present
    update_cache: true
- name: Install python3-devel.x86_64
  yum:
    name: python3-devel.x86_64
    state: present
    update_cache: true