- name: Install python3.x86_64
  yum:
    name: python3.x86_64
    state: present
    update_cache: true
- name: Install python3-pip.noarch
  yum:
    name: python3-pip.noarch
    state: present
    update_cache: true
- name: Install python3-devel.x86_64
  yum:
    name: python3-devel.x86_64
    state: present
    update_cache: true
- name: Install python3-devel.x86_64
  yum:
    name: mysql
    state: present
    update_cache: true
- name: Install lxml pour ansible nexus module
  pip:
    name: lxml
    executable: pip3
- name: Install flask
  become_user: devops
  become: true
  pip:
    name: flask
    executable: pip3
    extra_args: --user
- name: Install pymysql
  become_user: devops
  become: true
  pip:
    name: pymysql
    executable: pip3
    extra_args: --user
- name: Install pymysql
  become_user: devops
  become: true
  pip:
    name: pymysql
    executable: pip
    extra_args: --user
- name: Install python3.9 pour pipenv
#  become_user: devops
  become: true
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - gcc
    - openssl-devel
    - bzip2-devel
    - libffi-devel
- name: Install python3-devel.x86_64
  yum:
    name: sqlite-devel.x86_64
    state: present
    update_cache: true