- name: Creates directory ~/app
  become_user: devops
  become: true
  file:
    path: ~/app
    state: directory
    owner: devops
    group: devops
    mode: '0766'

- name: Download nexus build
  become_user: devops
  become: true
  get_url:
    url: http://{{ dnsnexus }}:8081/repository/APP/1/qcm-{{ansible_environnement}}/1.0-{{ numbuild }}/qcm-1.0-{{ numbuild }}.tar.gz
    dest: ~/app
    username: "{{ adminnexus }}"
    password: "{{ pwdnexus }}"

- name: Extract ~/app/qcmxxx.tar.gz
  become_user: devops
  become: true
  unarchive:
    src: ~/app/qcm-1.0-{{ numbuild }}.tar.gz
    dest: ~/app
    remote_src: yes

- name: Add another bin dir to system-wide $PATH
  become_user: devops
  become: true
  lineinfile:
    dest: /home/devops/.bashrc
    line: 'PATH=$PATH:/home/devops/.local/bin:/usr/local/bin'












