- name: Install python3.x86_64
  yum:
    name: python3.x86_64
    state: present
    update_cache: true

- name: Install python3-pip.noarch
  yum:
    name: python3-pip.noarch
    state: present
    update_cache: true

- name: Install python3-devel.x86_64
  yum:
    name: python3-devel.x86_64
    state: present
    update_cache: true

- name: Install mysql
  yum:
    name: mysql
    state: present
    update_cache: true

- name: Install MySQL-python
  yum:
    name: MySQL-python
    state: present
    update_cache: true

- name: Install python2-pip
  yum:
    name: python2-pip
    state: present
    update_cache: true

- name: Install lxml pour ansible nexus module
  pip:
    name: lxml
    executable: pip3

- name: Install flask
  pip:
    name: flask
    executable: pip3
    extra_args: --user

- name: Install pymysql
  pip:
    name: pymysql
    executable: pip3
    extra_args: --user
    
- name: Install pymysql
  pip:
    name: pymysql
    executable: pip2
    extra_args: --user

- name: Install python3.9 pour pipenv
#  become_user: devops
  become: true
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - gcc
    - openssl-devel
    - bzip2-devel
    - libffi-devel
    
- name: Install python3-devel.x86_64
  yum:
    name: sqlite-devel.x86_64
    state: present
    update_cache: true

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.33.11
  tags: nvm

- name: Source nvm in ~/.{{ item }}
  lineinfile: >
      dest=~/.{{ item }}
      line="source ~/.nvm/nvm.sh"
      create=yes
  tags: nvm
  with_items:
    - bashrc
    - profile

- name: Install node and set version
  become: yes
  become_user: root
  shell: "source /root/.nvm/nvm.sh && nvm install 8.11.3" 
  args:
    executable: /bin/bash 

 