
# - name: Create EC2 instance
#   include_tasks: cloudformation-create.yml
#   tags:
#     - cloudcreate: "ansible-cloudformation-create"

- name: Create devops user + distribution de la clé ssh
  include_tasks: add-user-ssh.yml

- name: Installation des package
  include_tasks: install-pkg.yml ansible_python_interpreter=/usr/bin/python3
  vars:
    ansible_python_interpreter: /usr/bin/python2

# - name: Delete EC2 instance
#   include_tasks: cloudformation-delete.yml
#   tags:
#     - clouddelete: "ansible-cloudformation-delete"
#   when: GOTODEL == "yes"

- name: install qcm
  include_tasks: install-qcm.yml

