
# - name: Create EC2 instance
#   include_tasks: cloudformation-create.yml
#   tags:
#     - cloudcreate: "ansible-cloudformation-create"



- name: Installation des package
  include_tasks: install-pkg.yml
  vars:
    ansible_python_interpreter: /usr/bin/python2

# - name: Delete EC2 instance
#   include_tasks: cloudformation-delete.yml
#   tags:
#     - clouddelete: "ansible-cloudformation-delete"
#   when: GOTODEL == "yes"

- name: Preparation install qcm + testDB
  include_tasks: install-qcmtestDB.yml

- name: Preparation install qcm
  include_tasks: install-qcm.yml
  tags:
    - qcmdb: "install-qcm-db"
  when: "{{ gotoqcm }}"  == yes