
# - name: Create EC2 instance
#   include_tasks: cloudformation-create.yml
#   tags:
#     - cloudcreate: "ansible-cloudformation-create"



- name: Installation des package
  include_tasks: install-pkg.yml
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: gotoqcm  == "no"

# - name: Delete EC2 instance
#   include_tasks: cloudformation-delete.yml
#   tags:
#     - clouddelete: "ansible-cloudformation-delete"
#   when: GOTODEL == "yes"

- name: Preparation install qcm 1
  include_tasks: install-qcm-upload.yml
  when: gotoqcm  == "no"

# - name: Preparation install qcm 2
#   include_tasks: install-qcm.yml
#   when: gotoqcm  == "yes"

  