version: '3'
services:

  # ajout d'un service mysql
  mysql-app:
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db.quizz
      MYSQL_USER: user.quizz
      MYSQL_PASSWORD: dru98eDFC90
      MYSQL_ROOT_PASSWORD: password
    volumes:
      #- /var/lib/mysql # volume anonyme, perd ses données  après un "down"
      - db_vol:/var/lib/mysql # volume nommé
  
  # ajout d'un service mysql de test
  mysql-test:
    image: 'mysql:5.7'
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: test.db.quizz
      MYSQL_USER: test.user.quizz
      MYSQL_PASSWORD: dtu896DCYUdf
      MYSQL_ROOT_PASSWORD: password
    volumes:
      #- /var/lib/mysql # volume anonyme, perd ses données  après un "down"
      - db_vol_test:/var/lib/mysql # volume nommé
    
  admin-db:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOSTS: mysql-app,mysql-test

# section volumes pour options
volumes:
  db_vol:
  db_vol_test: